import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import ScrollButton from "@/app/(baselayout)/components/ScrollButton";
import loginImage from "../../public/ico_login.svg";
import cartImage from "../../public/ico_bag.svg";
import joinImage from "../../public/ico_join.svg";
import logoImage from "../../public/ico_gnb_logo_176.svg";
import Image from "next/image";
// import { useState } from "react";
import Category from "./(baselayout)/components/category";
import ReduxProvider from "@/reducers";
import { MSWComponent } from "@/app/_component/MSWcomponent";
import Header from "@/app/_component/header";
import AuthSession from "@/app/_component/AuthSession";

const inter = Inter({ subsets: ["latin"] });
//페이지밖, 페이지에서 공유하고싶은것들을 작성한다.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// 헤더,검색창 띄우기
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header></Header>

          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
